name = "labelit-ai"
main = "src/worker.ts"
compatibility_date = "2022-04-05"

[vars]
CACHE_TTL = "3600"
CACHE_NAMESPACE = "labelit-ai"
MODEL_NAME = "@cf/meta/llama-3.1-8b-instruct"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "bf906e569452444faa2bca65bc582a8c"
